apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - certificate.yaml
  - gateway-api.yaml
  - gateway.yaml
  - ai-processor.yaml
  - cv-generator.yaml
images:
  - name: ghcr.io/corruptmane/cvgen-gateway
    newTag: main-9-7ed83bf # {"$imagepolicy": "flux-system:cvgen-gateway:tag"}
  - name: ghcr.io/corruptmane/cvgen-ai-processor
    newTag: main-9-7ed83bf # {"$imagepolicy": "flux-system:cvgen-ai-processor:tag"}
  - name: ghcr.io/corruptmane/cvgen-cv-generator
    newTag: main-9-7ed83bf # {"$imagepolicy": "flux-system:cvgen-cv-generator:tag"}
