apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
images:
  - name: ghcr.io/corruptmane/cvgen-migrate
    newTag: main-27-9a5814f # {"$imagepolicy": "flux-system:cvgen-migrate:tag"}
