apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
images:
  - name: ghcr.io/corruptmane/cvgen-migrate
    newTag: main-52-9af43e0 # {"$imagepolicy": "flux-system:cvgen-migrate:tag"}
