# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cvgen/events/v1/events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cvgen/events/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cvgen.cv.v1 import cv_pb2 as cvgen_dot_cv_dot_v1_dot_cv__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63vgen/events/v1/events.proto\x12\x0f\x63vgen.events.v1\x1a\x14\x63vgen/cv/v1/cv.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n\x0cJobRequested\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n\x0b\x63\x61reer_text\x18\x02 \x01(\tR\ncareerText\x12\'\n\x0fjob_description\x18\x03 \x01(\tR\x0ejobDescription\x12>\n\rpersonal_info\x18\x04 \x01(\x0b\x32\x19.cvgen.cv.v1.PersonalInfoR\x0cpersonalInfo\x12\x1b\n\tmodel_key\x18\x05 \x01(\tR\x08modelKey\x12;\n\x0boccurred_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt\"\x84\x01\n\rJobStructured\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n\x02\x63v\x18\x02 \x01(\x0b\x32\x0f.cvgen.cv.v1.CVR\x02\x63v\x12;\n\x0boccurred_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt\"\x87\x01\n\x0bJobRendered\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12$\n\x0epdf_object_key\x18\x02 \x01(\tR\x0cpdfObjectKey\x12;\n\x0boccurred_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt\"\xa6\x01\n\tJobFailed\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n\x05stage\x18\x02 \x01(\x0e\x32\x19.cvgen.events.v1.JobStageR\x05stage\x12\x14\n\x05\x65rror\x18\x03 \x01(\tR\x05\x65rror\x12;\n\x0boccurred_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt*X\n\x08JobStage\x12\x19\n\x15JOB_STAGE_UNSPECIFIED\x10\x00\x12\x18\n\x14JOB_STAGE_PROCESSING\x10\x01\x12\x17\n\x13JOB_STAGE_RENDERING\x10\x02\x42\xc9\x01\n\x13\x63om.cvgen.events.v1B\x0b\x45ventsProtoP\x01ZGgithub.com/corruptmane/cv/services/gateway/gen/cvgen/events/v1;eventsv1\xa2\x02\x03\x43\x45X\xaa\x02\x0f\x43vgen.Events.V1\xca\x02\x0f\x43vgen\\Events\\V1\xe2\x02\x1b\x43vgen\\Events\\V1\\GPBMetadata\xea\x02\x11\x43vgen::Events::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cvgen.events.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.cvgen.events.v1B\013EventsProtoP\001ZGgithub.com/corruptmane/cv/services/gateway/gen/cvgen/events/v1;eventsv1\242\002\003CEX\252\002\017Cvgen.Events.V1\312\002\017Cvgen\\Events\\V1\342\002\033Cvgen\\Events\\V1\\GPBMetadata\352\002\021Cvgen::Events::V1'
  _globals['_JOBSTAGE']._serialized_start=814
  _globals['_JOBSTAGE']._serialized_end=902
  _globals['_JOBREQUESTED']._serialized_start=105
  _globals['_JOBREQUESTED']._serialized_end=370
  _globals['_JOBSTRUCTURED']._serialized_start=373
  _globals['_JOBSTRUCTURED']._serialized_end=505
  _globals['_JOBRENDERED']._serialized_start=508
  _globals['_JOBRENDERED']._serialized_end=643
  _globals['_JOBFAILED']._serialized_start=646
  _globals['_JOBFAILED']._serialized_end=812
# @@protoc_insertion_point(module_scope)
