// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generations.sql

package db

import (
	"context"
	"encoding/json"
)

const createGeneration = `-- name: CreateGeneration :one
INSERT INTO generations (
    id, status, provider, model, experience_text, job_description, contacts
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, status, provider, model, experience_text, job_description, contacts, structured_cv, pdf_object_key, error, created_at, updated_at
`

type CreateGenerationParams struct {
	ID             string          `json:"id"`
	Status         string          `json:"status"`
	Provider       string          `json:"provider"`
	Model          string          `json:"model"`
	ExperienceText string          `json:"experience_text"`
	JobDescription string          `json:"job_description"`
	Contacts       json.RawMessage `json:"contacts"`
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.ID,
		arg.Status,
		arg.Provider,
		arg.Model,
		arg.ExperienceText,
		arg.JobDescription,
		arg.Contacts,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ExperienceText,
		&i.JobDescription,
		&i.Contacts,
		&i.StructuredCv,
		&i.PdfObjectKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGeneration = `-- name: GetGeneration :one
SELECT id, status, provider, model, experience_text, job_description, contacts, structured_cv, pdf_object_key, error, created_at, updated_at FROM generations WHERE id = $1
`

func (q *Queries) GetGeneration(ctx context.Context, id string) (Generation, error) {
	row := q.db.QueryRow(ctx, getGeneration, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ExperienceText,
		&i.JobDescription,
		&i.Contacts,
		&i.StructuredCv,
		&i.PdfObjectKey,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCompleted = `-- name: MarkCompleted :exec
UPDATE generations
SET status = 'completed', pdf_object_key = $2, updated_at = now()
WHERE id = $1
`

type MarkCompletedParams struct {
	ID           string `json:"id"`
	PdfObjectKey string `json:"pdf_object_key"`
}

func (q *Queries) MarkCompleted(ctx context.Context, arg MarkCompletedParams) error {
	_, err := q.db.Exec(ctx, markCompleted, arg.ID, arg.PdfObjectKey)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE generations
SET status = 'failed', error = $2, updated_at = now()
WHERE id = $1
`

type MarkFailedParams struct {
	ID    string `json:"id"`
	Error string `json:"error"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.ID, arg.Error)
	return err
}

const markStructured = `-- name: MarkStructured :exec
UPDATE generations
SET status = 'structured', structured_cv = $2, updated_at = now()
WHERE id = $1
`

type MarkStructuredParams struct {
	ID           string          `json:"id"`
	StructuredCv json.RawMessage `json:"structured_cv"`
}

func (q *Queries) MarkStructured(ctx context.Context, arg MarkStructuredParams) error {
	_, err := q.db.Exec(ctx, markStructured, arg.ID, arg.StructuredCv)
	return err
}
