// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"
	"time"
)

type Generation struct {
	ID             string          `json:"id"`
	Status         string          `json:"status"`
	Provider       string          `json:"provider"`
	Model          string          `json:"model"`
	ExperienceText string          `json:"experience_text"`
	JobDescription string          `json:"job_description"`
	Contacts       json.RawMessage `json:"contacts"`
	StructuredCv   json.RawMessage `json:"structured_cv"`
	PdfObjectKey   string          `json:"pdf_object_key"`
	Error          string          `json:"error"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}
