# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cvgen/catalog/v1/catalog.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cvgen/catalog/v1/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63vgen/catalog/v1/catalog.proto\x12\x10\x63vgen.catalog.v1\"\xd2\x01\n\x11ModelCatalogEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x36\n\x08provider\x18\x02 \x01(\x0e\x32\x1a.cvgen.catalog.v1.ProviderR\x08provider\x12\x19\n\x08model_id\x18\x03 \x01(\tR\x07modelId\x12!\n\x0c\x64isplay_name\x18\x04 \x01(\tR\x0b\x64isplayName\x12%\n\x0b\x64\x65scription\x18\x05 \x01(\tH\x00R\x0b\x64\x65scription\x88\x01\x01\x42\x0e\n\x0c_description*y\n\x08Provider\x12\x18\n\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x16\n\x12PROVIDER_ANTHROPIC\x10\x01\x12\x13\n\x0fPROVIDER_OPENAI\x10\x02\x12\x13\n\x0fPROVIDER_GOOGLE\x10\x03\x12\x11\n\rPROVIDER_FAKE\x10\x04\x42\xd1\x01\n\x14\x63om.cvgen.catalog.v1B\x0c\x43\x61talogProtoP\x01ZIgithub.com/corruptmane/cv/services/gateway/gen/cvgen/catalog/v1;catalogv1\xa2\x02\x03\x43\x43X\xaa\x02\x10\x43vgen.Catalog.V1\xca\x02\x10\x43vgen\\Catalog\\V1\xe2\x02\x1c\x43vgen\\Catalog\\V1\\GPBMetadata\xea\x02\x12\x43vgen::Catalog::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cvgen.catalog.v1.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.cvgen.catalog.v1B\014CatalogProtoP\001ZIgithub.com/corruptmane/cv/services/gateway/gen/cvgen/catalog/v1;catalogv1\242\002\003CCX\252\002\020Cvgen.Catalog.V1\312\002\020Cvgen\\Catalog\\V1\342\002\034Cvgen\\Catalog\\V1\\GPBMetadata\352\002\022Cvgen::Catalog::V1'
  _globals['_PROVIDER']._serialized_start=265
  _globals['_PROVIDER']._serialized_end=386
  _globals['_MODELCATALOGENTRY']._serialized_start=53
  _globals['_MODELCATALOGENTRY']._serialized_end=263
# @@protoc_insertion_point(module_scope)
